use_frameworks!
target 'Moya-Pretty_Tests' do
  pod 'Moya-Pretty', :path => '../'
  pod 'Moya-Pretty/ObjectMapper', :path => '../'
  pod 'Moya-Pretty/XMLDictionary', :path => '../'  
  pod 'Moya-Pretty/RESTful', :path => '../'
  pod 'Moya-Pretty/Plugins', :path => '../'
  pod 'Moya-Pretty/RxSwift', :path => '../'
  pod 'Moya-Pretty/PromiseKit', :path => '../'
  
  pod 'RxTest', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxBlocking'
  
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'RxNimble'
end
