use_frameworks!
target 'ObiMoyaExtension_Tests' do
  pod 'ObiMoyaExtension', :path => '../'
  pod 'ObiMoyaExtension/ObjectMapper', :path => '../'
  pod 'ObiMoyaExtension/RESTful', :path => '../'
  pod 'ObiMoyaExtension/Plugins', :path => '../'
  pod 'ObiMoyaExtension/RxSwift', :path => '../'
  pod 'ObiMoyaExtension/Promise', :path => '../'
  
  pod 'RxTest', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxBlocking'
  
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'RxNimble'
end
